force-app/main/default/objects/Case/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product Name</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Salesforce_Project__c.field-meta.xml
<CustomField>
    <fullName>Salesforce_Project__c</fullName>
    <description>Salesforce Project Name</description>
    <inlineHelpText>Salesforce Project Name</inlineHelpText>
    <label>Salesforce Project</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FetchCaseController.cls
/**
 * @Company           : Cloudkaptan Consultancy Services Pvt. Ltd.
 * @description       : This is used to
 * @author            : Arijit
 * @group             : 
 * @testclass         : 
 * @last modified on  : 04-07-2024
 * @last modified by  : Arijit Naskar
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   03-27-2024   Arijit   Initial Version
**/
public with sharing class FetchCaseController {
    
   
    /**
    * @description 
    * @author Arijit | 03-28-2024 
    * @param contactId
    * @return List<Case> 
    **/
    @AuraEnabled(cacheable = true)
    public static List<Case> getAllCases(String contactId){
        try {
            if(String.isBlank(contactId)) {
                contactId = '003U7000005ypG5IAI';
            }
            return [SELECT Id,
                        CaseNumber,
                        Status,
                        Subject,
                        Description,
                        Priority,
                        Contact.Name,
                        Type,
                        Salesforce_Project__c,
                        Product_Name__c
                        FROM Case 
                        WHERE ContactId =:contactId
                        WITH SYSTEM_MODE 
                        ORDER BY CreatedDate DESC
                        LIMIT 200];
        } catch (Exception ex) {
            throw new AuraHandledException(ex.getMessage());
        }
    }
}